camunda/dmn-scala

dmn-engine/src/main/scala/org/camunda/dmn/parser/DmnParser.scala, dmn-engine/src/test/resources/decisiontable/empty-expression.dmn, dmn-engine/src/test/scala/org/camunda/dmn/DmnEngineTest.scala
Handle empty expressions in the parser.
close #26
=> Fix NPE if a decision table has an empty input expression

dmn-engine/src/main/scala/org/camunda/dmn/parser/DmnParser.scala, dmn-engine/src/test/resources/config/decision_with_dash.dmn, dmn-engine/src/test/resources/config/decision_with_spaces.dmn, dmn-engine/src/test/scala/org/camunda/dmn/DmnEngineConfigurationTest.scala
* escape names with spaces or dashes using the supported symbol of the FEEL engine
closes #63
=> Escape names with the correct symbol

camunda-plugin/src/main/scala/org/camunda/dmn/camunda/plugin/CamundaDmnEngine.scala, camunda-plugin/src/main/scala/org/camunda/dmn/camunda/plugin/CamundaDmnEnginePlugin.scala, camunda-plugin/src/main/scala/org/camunda/dmn/camunda/plugin/CamundaDmnHistoryListener.scala, dmn-engine/src/main/scala/org/camunda/dmn/DmnEngine.scala, dmn-engine/src/test/scala/org/camunda/dmn/BkmTest.scala, dmn-engine/src/test/scala/org/camunda/dmn/ContextTest.scala, dmn-engine/src/test/scala/org/camunda/dmn/DecisionTableHitPolicyTest.scala, dmn-engine/src/test/scala/org/camunda/dmn/DecisionTableTest.scala, dmn-engine/src/test/scala/org/camunda/dmn/DecisionTest.scala, dmn-engine/src/test/scala/org/camunda/dmn/DmnEngineConfigurationTest.scala, dmn-engine/src/test/scala/org/camunda/dmn/DmnEngineTest.scala, dmn-engine/src/test/scala/org/camunda/dmn/DmnVersionCompatibilityTest.scala, dmn-engine/src/test/scala/org/camunda/dmn/FunctionDefinitionTest.scala, dmn-engine/src/test/scala/org/camunda/dmn/InvocationTest.scala, dmn-engine/src/test/scala/org/camunda/dmn/ListTest.scala, dmn-engine/src/test/scala/org/camunda/dmn/LiteralExpressionTest.scala, dmn-engine/src/test/scala/org/camunda/dmn/RelationTest.scala, dmn-engine/src/test/scala/org/camunda/dmn/RequiredDecisionTest.scala, dmn-engine/src/test/scala/org/camunda/dmn/spi/DmnEngineSpiTest.scala, engine-rest/src/main/scala/org/camunda/dmn/rest/DmnEngineRestServlet.scala, pom.xml, standalone-engine/src/main/scala/org/camunda/dmn/standalone/StandaloneEngine.scala, standalone-engine/src/test/scala/org/camunda/dmn/standalone/StandaloneEngineTest.scala, zeebe-worker/src/main/scala/org/camunda/dmn/zeebe/DmnJobHandler.scala
* change the engine API to include the audit log as part of the decision result
* the result type change from `Either[Failure, EvalResult]` to `Either[EvalFailure, EvalResult]` (= type alias `DecisionResult`)
* extend `EvalResult` by new properties `value` and `auditLog`
* change constructor of `Result` from `Result(value: Any)` to `Result(value: Any, auditLog: AuditLog)`
* change constructor of `NilResult` from `NilResult()` to `NilResult(auditLog: AuditLog)`
* change left side of the result from `Failure` to `EvalFailure(failure: Failure, auditLog: AuditLog)` 
closes #82
=> Evaluation result contains the audit log

dmn-engine/src/main/scala/org/camunda/dmn/DmnEngine.scala, dmn-engine/src/main/scala/org/camunda/dmn/evaluation/DecisionTableEvaluator.scala, dmn-engine/src/main/scala/org/camunda/dmn/evaluation/FunctionDefinitionEvaluator.scala, dmn-engine/src/main/scala/org/camunda/dmn/evaluation/InvocationEvaluator.scala, dmn-engine/src/main/scala/org/camunda/dmn/evaluation/LiteralExpressionEvaluator.scala, dmn-engine/src/main/scala/org/camunda/dmn/parser/DmnParser.scala, dmn-engine/src/main/scala/org/camunda/dmn/parser/ParsedDmn.scala, dmn-engine/src/test/resources/config/decision_with_invalid_expression.dmn, dmn-engine/src/test/resources/config/with_invalid_bkm.dmn, dmn-engine/src/test/resources/config/with_invalid_decision.dmn, dmn-engine/src/test/scala/org/camunda/dmn/DmnEngineConfigurationTest.scala, dmn-engine/src/test/scala/org/camunda/dmn/DmnEngineTest.scala
* add a new configuration option for lazy evaluation (default: `false`)
* if the option is enabled then it ignores failures on parsing
* instead, it writes log statements to make the failures visible (log level: `warning`)
* if an invalid expression is evaluated then it reports the failure
closes #81
=> Lazy decision evaluation

dmn-engine/src/main/scala/org/camunda/dmn/parser/DmnParser.scala, dmn-engine/src/test/resources/config/bkm_with_spaces_and_dash.dmn, dmn-engine/src/test/scala/org/camunda/dmn/DmnEngineConfigurationTest.scala
* escape parameter and formal parameter names when invoking a BKM if it is enabled in the configs
closes #72
=> Escape names from parameter in BKM

dmn-engine/src/main/scala/org/camunda/dmn/DmnEngine.scala, dmn-engine/src/test/resources/config/with_specific_date_time.dmn, dmn-engine/src/test/scala/org/camunda/dmn/DmnEngineConfigurationTest.scala
Adds an option to the DMN Engine Builder to pass in a custom FeelEngineClock.
A test case is added to uses the `now()` function to test that the provided custom clock is used by the engine.
closes #105
=> Add clock to DMN Engine Builder

README.md
The link to the value mapper documentation is not working anymore. I updated it to a correct href.
None.
=> chore: update value mapper link

dmn-engine/src/main/scala/org/camunda/dmn/parser/DmnParser.scala, dmn-engine/src/test/resources/decisiontable/adjustments_empty_output_name.dmn, dmn-engine/src/test/scala/org/camunda/dmn/DecisionTableTest.scala
* A decision table containing multiple outs will result in a NPE when one of these outputs does not define a name. In the parser we can verify that for all outputs a name is defined, or return a failure if it's not.
closes #142
=> Fail early on empty output name for decision table

dmn-engine/src/main/scala/org/camunda/dmn/parser/DmnParser.scala, dmn-engine/src/test/resources/requirements/cyclic-dependencies-in-decisions.dmn, dmn-engine/src/test/scala/org/camunda/dmn/DecisionTest.scala, dmn-engine/src/test/scala/org/camunda/dmn/DmnParserTest.scala
Opening this as draft PR for now. It does the job, but I feel there are a couple of points worth discussing first.
* in `DecisionTest` there is now this implicit class. Please let me know what you think of it, and in case you like it, whether we want to rewire the existing `parse(file)` calls to one of the new methods
* Not sure all the changes are idiomatic Scala. Any hints in that direction are very welcome
* In particular I am not happy about this construct:
```scala 
var foundCycle = false;
iterator.takeWhile(_ => !foundCycle).foreach(entry => foundCycle = doPartialCalculation(entry)
return foundCycle
```
* I made the assumption that it would be sufficient to detect the cycle, and it is not needed to return the elements of the cycle as part of the error message. Please let me know if …
=> Detect cyclic dependencies in decision requirements

dmn-engine/src/test/resources/spi/SpiTests.dmn, dmn-engine/src/test/scala/org/camunda/dmn/spi/DmnEngineSpiTest.scala, pom.xml
* dump `feel-engine` from `1.13.2` to `1.15.2`
* dump `camunda` from `7.16.0` to `7.18.0`
* adjust test case because of a reserved word
=> deps: dump feel-engine from 1.13.2 to 1.15.2

pom.xml
* ignore the Zeebe and the benchmark modules
* both modules will be removed soon.
=> build: ignore the Zeebe and benchmark modules

pom.xml
Generate a list of 3rd party dependencies. It can be used for a license boot.
closes #118
=> build: Generate 3rd party dependency list

api-check-ignore.xml, pom.xml, src/main/scala/org/camunda/dmn/parser/DmnParser.scala, src/test/resources/config/decision_with_spaces_in_item_definition_and_item_component.dmn, src/test/scala/org/camunda/dmn/DmnEngineConfigurationTest.scala
Allows spaces to be used in the names of `ItemDefinition`'s as per the DMN specification. Although `ItemDefinition`'s are not supported by Camunda Modeller, we have a customer need to import DMN models created in third-party DMN modelling tools for execution within the Camunda DMN engine.
See link in the related issues section for more details and context.
#150
=> Support for spaces in the names of `ItemDefinition`'s

pom.xml
The dependency `log4j-slf4j-impl` is not compatible with `slf4j2`. As a result, the DMN engine doesn't print any logging.
Replace the dependency with the compatible version `log4j-slf4j2-impl`.
=> deps: Replace log4j-slf4j-impl by log4j-slf4j2-impl

src/main/scala/org/camunda/dmn/Audit.scala, src/test/scala/org/camunda/dmn/AuditLogTest.scala, src/test/scala/org/camunda/dmn/DmnEngineTest.scala
If a decision is invoked with a non-existing decision id, the engine returns a failure with an empty audit log. This caused an exception because the audit log couldn't handle an empty list.
Remove the public properties `rootEntry` and `requiredEntries` from the audit log. These properties don't work if the audit log entries are empty.
Note that the property `rootEntry` may contain an audit log entry but no from the root decision. If the evaluation of a required decision fails, the engine doesn't add an entry for the root decision.
closes #135
=> fix: Handle the invocation of a non-existing decision

src/main/scala/org/camunda/dmn/parser/DmnParser.scala, src/test/resources/requirements/cyclic-dependencies-in-bkm.dmn, src/test/scala/org/camunda/dmn/DmnParserTest.scala
The engine fails the parsing of a DMN if it contains a cyclic dependency between BKMs.
closes #149
=> fix: Detect cyclic dependencies between BKMs

src/main/scala/org/camunda/dmn/parser/DmnParser.scala, src/test/resources/requirements/non-cyclic-nested-dependencies-in-decisions.dmn, src/test/scala/org/camunda/dmn/DmnParserTest.scala
In this model there is no cyclic dependency. The parser incorrectly gives a warning that there is a cyclic dependency.
The cause lays in the cyclic dependency check. This check takes a list of decisions it still needs to visit. It builds this list from the dependencies of previous decisions that have been checked.
The scoping of this check is wrong.  It checks the dependencies in a cyclic way for the entire DRG. With each cycle we append to the visited elements. Upon reaching an end state, we do not clear this list of visited elements.
For the example DRG this means:
1. We check for cyclic dependencies in C
2. We check for cyclic dependencies in A (visited C)
3. A doesn't have any more dependencies, yet we append it to the list of visited elements and continue with the other decisions
4. …
=> Fix incorrect cyclic dependency detection

pom.xml, src/main/scala/org/camunda/dmn/parser/DmnParser.scala, src/test/resources/dmn1.4/greeting.dmn, src/test/resources/dmn1.5/greeting.dmn, src/test/scala/org/camunda/dmn/DmnVersionCompatibilityTest.scala
* Support the new namespaces of DMN 1.4 and 1.5
* Dump the Camunda model-api to `7.20.0-alpha5`. This is the latest version that contains the support for the new namespaces.
closes #221
=> feat: Support namespaces of DMN 1.4 and 1.5

api-check-ignore.xml, pom.xml, src/main/scala/org/camunda/dmn/evaluation/BusinessKnowledgeEvaluator.scala, src/main/scala/org/camunda/dmn/evaluation/DecisionEvaluator.scala, src/main/scala/org/camunda/dmn/parser/DmnParser.scala, src/main/scala/org/camunda/dmn/parser/DmnRepository.scala, src/main/scala/org/camunda/dmn/parser/InMemoryDmnRepository.scala, src/main/scala/org/camunda/dmn/parser/ParsedDmn.scala, src/main/scala/org/camunda/dmn/parser/StatelessDmnRepository.scala, src/test/scala/org/camunda/dmn/DmnImportTest.scala
This addresses the following todos referenced in https://github.com/camunda/dmn-scala/pull/222:
related to https://github.com/camunda/dmn-scala/issues/71
closes #
=> 71 from poc - dynamic import loading

.github/workflows/deploy.yml
The secrets used for this workflow belongs to the `camunda-hub` user and the secret has now been migrated. See [this](https://github.com/camunda/team-infrastructure/issues/640#issuecomment-2195298760) comment on the related infra ticket 
https://github.com/camunda/team-infrastructure/issues/640
=> chore(maven-central-secrets): Update maven central secrets

src/main/scala/org/camunda/dmn/DmnEngine.scala
This PR lowers the log level of the initial engine creation log statement. The reasoning here is that almost all of the information provided here is only really useful for debugging, and generally not useful for the common user.
As this is mostly to reduce the noise-to-signal ratio in Zeebe, the alternative would be only showing WARN messages from this library (as we do with other libraries). That would also be acceptable to me, so feel free to reject this if you disagree, and we can go with the alternative :)
closes #305
=> refactor: lower log level to debug
